CUAD_LABELS = [
    "Termination",
    "Payment Terms",
    "Liability",
    "Limitation of Liability",
    "Confidentiality",
    "Non-Compete",
    "Intellectual Property",
    "Indemnification",
    "Assignment",
    "Governing Law",
    "Arbitration",
    "Insurance",
    "Data Protection",
    "Force Majeure",
    "Warranty",
    "Representations and Warranties",
    "Entire Agreement",
    "Amendments",
    "Notices",
    "Severability",
    "Waiver",
    "Survival",
    "Counterparts",
    "Definitions",
    "Expenses",
    "Publicity",
    "Subcontracting",
    "No Waiver",
    "Further Assurances",
    "No Third Party Beneficiaries",
]

CUAD_LABEL_DESCRIPTIONS = {
    "Termination": "Clauses describing termination rights, notice periods, termination for cause or convenience.",
    "Payment Terms": "Clauses specifying payment amounts, schedules, late fees, invoicing procedures.",
    "Liability": "Clauses defining liability scope, unlimited liability, caps, and exclusions.",
    "Limitation of Liability": "Clauses capping liability amounts or excluding certain damages.",
    "Confidentiality": "Clauses protecting confidential information, non-disclosure obligations, exceptions.",
    "Non-Compete": "Clauses restricting competitive activities during or after the contract term.",
    "Intellectual Property": "Clauses addressing IP ownership, licensing, assignments, and protections.",
    "Indemnification": "Clauses requiring one party to compensate for losses or damages.",
    "Assignment": "Clauses governing transfer of rights or obligations to third parties.",
    "Governing Law": "Clauses specifying which jurisdiction's laws govern the contract.",
    "Arbitration": "Clauses requiring disputes to be resolved through arbitration rather than courts.",
    "Insurance": "Clauses requiring insurance coverage, types, minimum amounts, and proof.",
    "Data Protection": "Clauses addressing data privacy, GDPR compliance, data processing, security measures.",
    "Force Majeure": "Clauses excusing performance due to extraordinary events outside control.",
    "Warranty": "Clauses providing guarantees about products, services, or performance.",
    "Representations and Warranties": "Clauses containing factual assertions and promises about the contracting parties.",
    "Entire Agreement": "Clauses stating the contract represents the complete agreement between parties.",
    "Amendments": "Clauses describing how the contract may be modified after execution.",
    "Notices": "Clauses specifying how formal communications between parties must be delivered.",
    "Severability": "Clauses ensuring remaining provisions stay valid if parts are unenforceable.",
    "Waiver": "Clauses addressing whether failure to enforce rights constitutes a waiver.",
    "Survival": "Clauses specifying which obligations continue after contract termination.",
    "Counterparts": "Clauses allowing the contract to be signed in multiple identical copies.",
    "Definitions": "Clauses containing defined terms and their meanings for the contract.",
    "Expenses": "Clauses addressing which party bears specific costs and expenses.",
    "Publicity": "Clauses restricting or governing public announcements about the agreement.",
    "Subcontracting": "Clauses addressing whether duties may be delegated to third parties.",
    "No Waiver": "Clauses stating that delay in enforcing rights does not waive them.",
    "Further Assurances": "Clauses requiring parties to execute additional documents to effectuate the agreement.",
    "No Third Party Beneficiaries": "Clauses stating that non-parties have no rights under the contract.",
}
